pipeline {
    agent any

    environment {
        PATH = "$HOME/development/flutter/bin:$PATH"
        PROJECT_PATH = "${env.JENKINS_HOME}/workspace/test"
        MOBILE_PATH = "${PROJECT_PATH}/flutter-new-project"
        MOBILE_SCRIPTS_PATH = "${MOBILE_PATH}/scripts"
    }

    stages {
        stage('Prepare') {
            steps {
                dir(PROJECT_PATH) {
                    sh '''
                        git pull --rebase origin main
                    '''
                }
                dir(MOBILE_PATH) {
                    sh '''
                        
                        flutter pub get
                    '''
                }
            }
        }

        stage('Test') {
            steps {
                dir(MOBILE_PATH) {
                    sh '''
                        flutter test test/widget_test.dart
                    '''
                }
            }
        }

        stage('Deployment') {
            steps {
                dir(MOBILE_PATH) {
                    sh '''
                        echo "Deployment"
                    '''
                }
            }
        }
    }
}
