pipeline {
    agent any

    // tools {nodejs "NodeJS"}
    // tools {
    //     flutter 'flutter'
    // }

    environment {
        PROJECT_PATH = "${env.JENKINS_HOME}/workspace/flutter_new_project/flutter_new_project"
        SCRIPTS_PATH = "${PROJECT_PATH}/scripts"
        PATH = "$HOME/development/flutter/bin:$PATH"
        BRANCH_NAME="main"
        ROOT_PATH="${env.JENKINS_HOME}/workspace"
    //     DEV="dev"
    //     ALPHA="alpha"
    //     PREPROD="preprod"
    //     PROD="prod"
    //     WEB_PATH="${PROJECT_PATH}/web"
    //     TEST_PATH="${PROJECT_PATH}/e2e-web"
    }

    stages {
        stage('Pulling') {
            steps {
                dir(ROOT_PATH) {
                    script {
                        echo 'Pulling stage'
                        sh "git checkout ${BRANCH_NAME}"
                        sh "git pull --rebase origin ${BRANCH_NAME}"
                    }
                }
            }
        }

        stage('Build') {
            steps {
                dir(PROJECT_PATH) {
                    echo 'Build stage'
                    sh '''
                        flutter pub get
                        flutter build apk --release
                    '''
                }
            }
        }

        stage('Test') {
            steps {
                dir(PROJECT_PATH) {
                    echo 'Test stage'
                    sh '''
                        flutter test test/widget_test.dart
                    '''
                }
                
            }
        }

        stage('Deployment') {
            steps {
                dir("${SCRIPTS_PATH}") {
                    sh '''
                        echo "Deployment"
                    '''
                }
            }
        }
    }
}
