pipeline {
    agent any

    environment {
        PATH = "$HOME/development/flutter/bin:$PATH"
        PROJECT_PATH = "${env.JENKINS_HOME}/workspace/test"
        MOBILE_PATH = "${PROJECT_PATH}/flutter_new_project"
        MOBILE_SCRIPTS_PATH = "${MOBILE_PATH}/scripts"
    }

    stages {
        stage('Build') {
            steps {
                dir(MOBILE_PATH) {
                    echo 'Build stage'
                    sh '''
                        flutter pub get
                        flutter build apk --release
                    '''
                }
            }
        }

        stage('Test') {
            steps {
                dir(MOBILE_PATH) {
                    echo 'Test stage'
                    sh '''
                        flutter test test/widget_test.dart
                    '''
                }
            }
        }

        stage('Deployment') {
            steps {
                dir(MOBILE_PATH) {
                    sh '''
                        echo "Deployment"
                    '''
                }
            }
        }
    }
}
