pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="${env.JENKINS_HOME}/workspace/testing-strategy-3/testing-strategy-3"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
        WEB_PATH="${PROJECT_PATH}/web"
        TEST_PATH="${PROJECT_PATH}/e2e-web"
    }

    stages {
        // stage('Build') {
        //    steps {
        //         dir("${SCRIPTS_PATH}") {
        //             sh """
        //             echo "Build"
        //             """
        //         }
        //     }
        // }
        stage('Test environment DEV') {
            steps {
                // dir("${SCRIPTS_PATH}") {
                //    sh """
                //     echo "Test"
                //     """
                // }
                dir("${WEB_PATH}") {
                    sh """
                    npm install
                    npm run start &
                    """
                }
                dir("${TEST_PATH}") {
                    sh """
                    npm run test
                    """
                }
            }
            post {
                always {
                    dir("${SCRIPTS_PATH}") {
                        sh """
                        ./application-management.sh close
                        """
                    }
                    dir("${SCRIPTS_PATH}") {
                        sh """
                        ./report.sh generate
                        """
                    }
                }
            }
        }
        
        // stage('Deployment') {
        //     steps {
        //         dir("${SCRIPTS_PATH}") {
        //            sh """
        //             echo "Deployment"
        //             """
        //         }
        //     }
        // }
    }
}