pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="${env.JENKINS_HOME}/workspace/testing-strategy-3/testing-strategy-3"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
        WEB_PATH="${PROJECT_PATH}/web"
    }

    stages {
        // stage('Build') {
        //    steps {
        //         dir("${SCRIPTS_PATH}") {
        //             sh """
        //             echo "Build"
        //             """
        //         }
        //     }
        // }
        stage('Test environment DEV') {
            steps {
                // dir("${SCRIPTS_PATH}") {
                //    sh """
                //     echo "Test"
                //     """
                // }
                dir("${WEB_PATH}") {
                    sh """
                    npm install
                    """
                }
            }
        }
        // stage('Deployment') {
        //     steps {
        //         dir("${SCRIPTS_PATH}") {
        //            sh """
        //             echo "Deployment"
        //             """
        //         }
        //     }
        // }
    }
}